### ISSUE TITLE
> 2 Million Rows

### ISSUE THREAD

**Issue by jcohlmeyer** [glimpseio/Splice#6]
This product works great, however when I try to open a table with over 2 million rows the query does not succeed (using PostgreSQL on AWS RDS).

The program reports `ERROR: canceling statement due to user request` even though I did not make another request.

**Comment by marcprux** [comment]
Thanks for the report. Splice should be able to handle arbitrarily large result sets, because it uses database cursors to only load a few records at a time. It may be that the query itself isn't returning anything within the default timeout. Can you try opening the app preferences, and under the "General" tab, changing the "Default Network Timeout" to something higher, and trying your query again? You will probably need to disconnect and then re-connect to the database (or else just quit and restart Splice).

Please let us know if that helps, or if you are still getting the same error.

**Comment by jcohlmeyer** [comment]
Okay, it works, I set the "Default Network Timeout" to unlimited and the results are all returned, and the app works quite well given how many results there are.

Perhaps you could edit the error message for this case indicating that the select timed out and suggest increasing the default time out.

**Comment by marcprux** [comment]
Glad that worked! We will try to improve the error message there, since I agree that it is a bit deceptive.
